version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_stampiza2
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

volumes:
  mongodb-data:
